"use client";

import Image from "next/image";
import { Button } from "@/components/ui/button";
import { useState } from "react";
import { Wand2 } from "lucide-react";
import { Card, CardContent } from "../ui/card";

const placeholderImages = [
  {
    prompt: "A futuristic hairstyle with bioluminescent highlights.",
    src: "https://placehold.co/512x512.png",
    hint: "futuristic hairstyle",
  },
  {
    prompt: "Intricate nail art inspired by a mystical forest.",
    src: "https://placehold.co/512x513.png",
    hint: "nail art",
  },
  {
    prompt: "A dramatic, avant-garde makeup look with gold leaf.",
    src: "https://placehold.co/512x514.png",
    hint: "avant-garde makeup",
  },
  {
    prompt: "A serene spa room with a view of a cherry blossom garden.",
    src: "https://placehold.co/512x515.png",
    hint: "spa room",
  },
];

export function AiGallery() {
  const [images, setImages] = useState(placeholderImages);
  const [isLoading, setIsLoading] = useState(false);

  const generateImages = async () => {
    setIsLoading(true);
    // In a real application, you would call your AI image generation flow here.
    // For now, we'll just simulate a delay.
    setTimeout(() => {
      // You could replace existing images or add new ones.
      // For this example, we'll just keep the placeholders.
      setIsLoading(false);
    }, 2000);
  };

  return (
    <section id="ai-gallery" className="py-20 md:py-32">
      <div className="container mx-auto px-4 md:px-6">
        <div className="text-center mb-12">
          <h2 className="font-headline text-3xl md:text-4xl font-bold">
            AI-Powered Inspirations
          </h2>
          <p className="mt-2 text-muted-foreground max-w-2xl mx-auto">
            Explore unique beauty concepts generated by our creative AI.
          </p>
          <Button onClick={generateImages} disabled={isLoading} className="mt-6">
            <Wand2 className="mr-2" />
            {isLoading ? "Generating..." : "Generate New Styles"}
          </Button>
        </div>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
          {images.map((image, index) => (
            <Card
              key={index}
              className="group overflow-hidden rounded-lg shadow-lg hover:shadow-2xl transition-all duration-300"
            >
              <CardContent className="p-0">
                <div className="relative aspect-square">
                  <Image
                    src={image.src}
                    alt={image.prompt}
                    data-ai-hint={image.hint}
                    fill
                    className="object-cover transition-transform duration-300 group-hover:scale-105"
                  />
                  <div className="absolute inset-0 bg-black/40 opacity-0 group-hover:opacity-100 transition-opacity duration-300 flex items-end p-4">
                    <p className="text-primary-foreground text-sm">
                      {image.prompt}
                    </p>
                  </div>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      </div>
    </section>
  );
}
